---
title: "Figure2"
output: html_document
---

```{r loading_libraries}
#install.packages(c("ggplot2", "dplyr", "rnaturalearth", "rnaturalearthdata"))
#install.packages("gganimate") 

library(gganimate)
library(ggplot2)
library(dplyr)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)         

world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

```

``` {r}
world <- ne_countries(scale = "medium", returnclass = "sf")
world_data <- world %>%
  left_join(df, by = c("iso_a3" = "iso3c"))

df <- df %>% filter(year >= 1960 & year <= 2024)

p <- ggplot(world_data) +
  geom_sf(aes(fill = gdppc), color = "gray30", size = 0.2) +
  scale_fill_viridis_c(option = "plasma", na.value = "lightgray",
                       name = "GDP per Capita") +
  labs(
    title = "World GDP per Capita: {closest_state}",
    caption = "Source: V-Dem Dataset v13; World Bank World Development Indicators (GDP per capita)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "left",
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5)
  ) +
  transition_states(
    year,
    transition_length = 1,
    state_length = 1
  ) +
  ease_aes("linear")

animate(p,
  nframes = 200,
  fps = 10,
  width = 900, height = 600,
  renderer = gifski_renderer("world_gdppc_1960_2024.gif")
)

```

``` {r map-of-polyarchies}
pal <- colorNumeric("YlGnBu", domain = df$value, na.color = "lightgrey")

leaflet(world_data) |>
  addTiles() |>
  addPolygons(
    fillColor = ~pal(gdp),
    color = "white",
    weight = 1,
    popup = ~paste(name, "<br>gdp:", gdp)
) |>
  setView(lng = 0, lat = 20, zoom = 2)
```

```{r gdp-2024-map}
year_to_plot <- 2024
map_data_year <- df |> 
  filter(year == year_to_plot)

world <- ne_countries(scale = "medium", returnclass = "sf")

world_data <- world %>%
  left_join(map_data_year, by = c("iso_a3" = "countryid"))

ggplot(data = world_data) +
  geom_sf(aes(fill = gdppc), color = "gray30", size = 0.2) +
  scale_fill_viridis_c(na.value = "lightgray",
                       name = "GDP per Capita") +
  labs(
    title = paste("World GDP per Capita in", year_to_plot)
  ) +
  theme_minimal() +
  theme(
  axis.text = element_blank(),
  axis.ticks = element_blank(),
  legend.position = "left",
  plot.title = element_text(size = 16, face = "bold", hjust = 0.5)
)
```
```{r Democracy-2024-map}
year_to_plot <- 2024
map_data_year <- df |> 
  filter(year == year_to_plot)

world <- ne_countries(scale = "medium", returnclass = "sf")

world_data <- world %>%
  left_join(map_data_year, by = c("iso_a3" = "countryid"))

ggplot(data = world_data) +
  geom_sf(aes(fill = libdem), color = "gray30", size = 0.2) +
  scale_fill_viridis_c(na.value = "lightgray",
                       name = "Liberal Dem. Index") +
  labs(
    title = paste("World Liberal Democracy in", year_to_plot)
  ) +
  theme_minimal() +
  theme(
  axis.text = element_blank(),
  axis.ticks = element_blank(),
  legend.position = "left",
  plot.title = element_text(size = 16, face = "bold", hjust = 0.5)
)
```


